### ISSUE TITLE
Update for gnome 3.36

### ISSUE THREAD

**Issue by jacobmischka** [spin83/multi-monitors-add-on#111]
Just creating this tracking issue now after updating to 3.36, the extension seems to error on start.

I'll try to dig into this soon and hopefully put together a PR.

Thanks!

**Comment by RaphaelRochet** [comment]
I wish you luck and good understanding of recent Gnome changes :)
For what I've seen, there's lots of deprecated/obsolete calls around. I tried to dig into it but got lost quickly.

**Comment by realh** [comment]
It doesn't work properly in Gnome 3.35 either. Its icon appears in the systray and I can open its Preferences etc, but the panel doesn't appear on the second monitor. LookingGlass reports no errors.

**Comment by smcv** [comment]
(For context: I don't use this extension myself, but I'm going through GNOME Shell extensions that are packaged in Debian and making sure there are issues open to get them adapted to an upstream change.)

One thing that isn't going to work in 3.36 is that this extension contains:

```
Util.spawn(["gnome-shell-extension-prefs", "multi-monitors-add-on@spin83"]);
```

which will not work since GNOME Shell 3.36.1, because the way extension preferences work has been redone to accommodate the g-s-extension-prefs app being installed via Flatpak or similar.

As far as I can tell from GNOME Shell's upstream commit history, the preferred way to launch extension preferences in sufficiently recent versions is to call imports.misc.extensionUtils.openPrefs(), which was added by [gnome-shell!1163](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1163). The version in Ubuntu 20.04 doesn't have that function available yet, but hopefully will soon; Debian experimental already has it.

To support older GNOME versions, fall back to the spawn call if imports.misc.extensionUtils doesn't have an openPrefs method.

Sample code: [Tudmotu/gnome-shell-extension-clipboard-indicator#203](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/203)

**Comment by BloodyIron** [comment]
Duplicate to #107 . Reported it months ago, yet somehow this one gets more attention? Hopefully this gets fixed. I've had this addon throw errors for many months now on all systems that use it. :(

**Comment by jacobmischka** [comment]
I've been using the wip_gnome_3_36 branch successfully for a couple weeks, haven't noticed any issues :+1:

**Comment by BloodyIron** [comment]
Well hopefully that branch goes release soon so we can install it from the proper repos! :D Glad to hear fixes are in there :+1:

**Comment by realh** [comment]
For me (upgraded to GNOME 3.36.1 since my last comment) wip_gnome_3_36 fixes basic functionality but I can't open the Preferences. I guess this means the issue in @smcv's [comment](https://github.com/spin83/multi-monitors-add-on/issues/111#issuecomment-610692744) hasn't been fixed yet?

**Comment by realh** [comment]
I've got `wip_gnome_3_36` to support opening preferences in gnome-shell 3.36.1 by copying the dbus call from gnome-shell git to the extension's code. I haven't submitted a PR, because I don't know whether this code is forwards and/or backward compatible and how best to support all versions if not. But here's a patch.

[prefs-3.36.1.diff.txt](https://github.com/spin83/multi-monitors-add-on/files/4512713/prefs-3.36.1.diff.txt)

**Comment by edalongeville** [comment]
Using `wip_gnome_3_36` on Manjaro (Gnome 3.36.1) causes the following error message in the console:
`TypeError: this._onButtonPress is undefined`

**Comment by BloodyIron** [comment]
Woot! Just got the update, so far no errors thrown, but we'll see if that holds up :sunglasses:

**Comment by spin83** [comment]
@edalongeville please try the current version of this extension (v20), it now works with Gnome 3.36.

**Comment by edalongeville** [comment]
The new release works on both Gnome 3.36.1 and 3.36.2.

Thanks a lot @spin83 !
I can't believe the second thumbnail slider isn't a default feature of gnome.
