### ISSUE TITLE
Top bar on secondary display is missing the drag window capability

### ISSUE THREAD

**Issue by raelgc** [spin83/multi-monitors-add-on#116]
I use this extension to apply the Gnome top bar to both displays (and it works great, thanks!)

Some CSD applications (i.e., no system title bar, like Firefox or Chrome) can only be dragged clicking in the Gnome top bar and then can be moved/drop in the secondary display.

But once they're in the **secondary** display, the click-to-drag in the Gnome topbar is missing, so CSD applications have no way to be dragged between monitors.

It's worst if user is using "no titlebar" extensions: click in the Gnome topbar to drag is the only way to drag a window.

**Comment by raelgc** [comment]
Oh, I can see that on commit 15a0d3ceea6a601d4c4b709a0fd655ff7d6d27ea, some panel events are no more connected.

I tried to remove the version check and it failed saying the related event is `undefined` (probably the reason why they're disabled now).

Anyway, I can see that 3.36 branch is still a working in progress, so maybe there is hope for this! :)

**Comment by raelgc** [comment]
Ok, I think I got this working. I'll spend sometime testing, then I'll submit a PR.

**Comment by raelgc** [comment]
Just sent a PR: #117

**Comment by raelgc** [comment]
Oh, I can see you fixed just implementing the correct checking on `_getDraggableWindowForPosition`. I'll close my PR and this issue. Really thanks!

**Comment by arisoda** [comment]
Not 100% sure if this is what it describes to do, but YES I'm all in for this feature. It has since been merged with master but why is it 3 years later not present in master? Isn't this about the ability to click and drag the top panel (when a window is maximized on that same monitor) to subsequently drag the window around? How come it is not present since the merger in 2020? @raelgc
