### ISSUE TITLE
Does not work on GNOME 3.38

### ISSUE THREAD

**Issue by jvnknvlgl** [spin83/multi-monitors-add-on#137]
The extension does not work on GNOME 3.38. It gives the following error in the Extensions application:

's is undefined'

I'm using the Fedora 33 pre-release.

**Comment by jacobmischka** [comment]
I've dug into this a little bit.

They removed the Calendar.EventsSection, so all of the code in `mmcalendar.js` related to it needs to be stripped or disabled in 3.38.

Then, `Tweener` was removed in 3.38, so all of the calls to Tweener need to be stripped out (this can be done relatively easily by dropping 3.32 support and removing the icon hello function that doesn't even seem to be called anywhere.

Once those changes are made the extension will activate without errors, but the overview is pretty broken and doesn't align/sync well. They changed a lot about how geometries are updated since 3.36 it seems. This is where I'm stuck now.

**Comment by fdinardo** [comment]
Is this extension dropped?

**Comment by asterlab** [comment]
patch anyone ?

**Comment by Jhackler** [comment]
usually takes a bit after this extension breaks before it gets fixed/ updated. really wish gnome would just give decent multi-monitor option by default

**Comment by Jhackler** [comment]
keep up the good work though, I appreciate it.

**Comment by toupeira** [comment]
@spin83 thank you, latest `master` fixed it for me on Gnome 3.38.1! :tada:

**Comment by jacobmischka** [comment]
Can also confirm that it works again, but the animations are a bit clunky when the switcher panel is enabled on non-primary monitors. Regardless, great work and thanks for the quick update!

**Comment by asterlab** [comment]
Is there a way to have this from the gnome extensions site ?

**Comment by jvnknvlgl** [comment]
@asterlab it would be nice if you coud be a little patient. 

Your comment 'patch anyone ?' does not contribute anything to this issue, and comes across as very rude. The developer does this work free of charge, and is in no way obligated to provide this work to you or any other user. 

If the developer feels like the code is in a proper state, he or she might decide to upload it on the GNOME Extensions website. You, as a regular user, have two options: wait and see, or actively contribute yourself. The latter option is, of course, possible because this is a GPL 2-licensed project.

**Comment by fdinardo** [comment]
Thanks @spin83 that worked on gnome 3.38. Great work and great extension. I can't imagine why the gnome team doesn't provide this by default. 

About my previous comment, I was just wondering if this extension was dropped, in case, I would have made a fork and try to fix by myself, but with a very long deadline, since I am not an expert developing gnome extensions.

Thanks again!

**Comment by fulljackz** [comment]
Great work, thanks for all of Ubuntu 20.10 / Gnome 3.38 users :+1:

**Comment by RSWilli** [comment]
whats the state on this? if it is working, why was the gnome extensions repo not updated?

are there still problems / needed improvements involving the current implementation?

**Comment by highvoltage** [comment]
@spin83 According to reports above, it seems that master is working in 3.38.1, do you think you can tag a new release?

**Comment by grizzlysmit** [comment]
Yeah just found out about this whats the ETA on a fix, even a partial one

**Comment by grizzlysmit** [comment]
The main/master is working to some degree on my box, with 3.38.1 on ubuntu 20.10 very happy

**Comment by grizzlysmit** [comment]
hmm the version I grabbed  from github seams to leave me with no borders etc on windows any idea when the plugin will be totally fixed

**Comment by spin83** [comment]
Should work with gnome-shell 3.38.1 . Could you be more specific about what you mean by "no borders etc on windows" maybe you can put a screenshot. You're using Ubuntu 20.10, right?

**Comment by grizzlysmit** [comment]
uumm here's a screen shot of a gvim session though it happens with everything else too
![2020-11-08T06 39 41-gvim-sans-borders-1468x850](https://user-images.githubusercontent.com/9037046/98450176-b8892380-218e-11eb-8a15-574e9526fd67.png)
though  maybe it some thing else doing it would love to know though

**Comment by grizzlysmit** [comment]
and yes I am using Ubuntu 20.10 but it does not happen on single monitor systems, but I do not have this plugin on them as well only single monitors

**Comment by grizzlysmit** [comment]
stop press I've found the culprit it's Argos https://extensions.gnome.org/extension/1176/argos/ that does it was going through the diff's between this and the single monitor system and this and Argos were it, so I switched Argos off and the problem went away, sorry for the bother.

**Comment by grizzlysmit** [comment]
maybe not I've uninstalled Argos and the problem cam back

**Comment by grizzlysmit** [comment]
Hmm even when I switched off Multi Monitors Add-On the problem persisted I have to dig deeper

**Comment by jacobmischka** [comment]
Confirming that animations look perfect after the recent commit, great work :+1:. Thanks again!

**Comment by Random-Chain** [comment]
On Gnome 3.36.3, running master commit b326bb3e67304a78176c060537bca796c2b112dd.

I'm getting this error:
`Nov 16 17:33:18 system gnome-shell[2447]: JS WARNING: [/home/user/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmcalendar.js 115]: reference to undefined property "EventsSection"
Nov 16 17:33:18 system gnome-shell[2447]: JS ERROR: Extension multi-monitors-add-on@spin83: TypeError: s is undefined
#012copyClass@/home/user/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/extension.js:43:25
#012MultiMonitorsEventsSection<@/home/user/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmcalendar.js:115:19
#012@/home/user/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmcalendar.js:117:3
#012@/home/user/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmpanel.js:31:20
#012@/home/user/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:17:17
#012@/home/user/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/extension.js:30:18
#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:425:13
#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:346:27
#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
#012start@resource:///org/gnome/shell/ui/main.js:146:5
#012@<main>:1:47`

Is this issue not fixed in master? Or is there something else I should do?

**Comment by spin83** [comment]
Version 22 and the [master](https://github.com/spin83/multi-monitors-add-on/tree/master) branch are not compatible with gnome-shell 3.36.x
Please use an older version or the [gnome-3-32_3-36](https://github.com/spin83/multi-monitors-add-on/tree/gnome-3-32_3-36) branch.
