### ISSUE TITLE
Overview windows and thumbnail slider on gnome-shell 3.26.1 Arch

### ISSUE THREAD

**Issue by dupkey** [spin83/multi-monitors-add-on#57]
As some people have mentioned on the Gnome Extensions page I am also having an issue with overview windows not showing on secondary displays and the thumbnail slider almost completely cropped out on secondary displays.

Btw, thanks for the awesome extension!

**Comment by alozytskyi** [comment]
![screenshot from 2017-10-11 11-16-00](https://user-images.githubusercontent.com/25198154/31430320-346694d8-ae79-11e7-9317-cea69a62e32d.png)

**Comment by alozytskyi** [comment]
This is how it looks on second monitor. Also you can notice that chrome window is not shown in the list but is seen on the corner of the thumbnail.

**Comment by mallardduck** [comment]
Just so anyone else that has this issue is aware, if you pull the [wip_gnome_3_26](https://github.com/spin83/multi-monitors-add-on/tree/wip_gnome_3_26) branch then this should be fixed.

I was seeing both this issue and one where the last monitors windows would disappear, but on the new branch all seems to be working!

**Comment by hswong3i** [comment]
Confirm that [wip_gnome_3_26](https://github.com/spin83/multi-monitors-add-on/tree/wip_gnome_3_26) working with Ubuntu 17.10 + Gnome 3.26 ;-)

**Comment by dupkey** [comment]
Working correctly now with the wip_gnome_3_26 branch on 4.13.5-1-ARCH gnome-shell 3.26.1
