### ISSUE TITLE
gnome-shell trap when unlocking, loss of unsaved work

### ISSUE THREAD

**Issue by Zvezdin** [spin83/multi-monitors-add-on#58]
Arch Linux x64, proprietary NVIDIA driver, Gnome 3 on xorg. All to latest versions including multi-monitors extension.

My setup includes two monitors: one 1920x1200 (secondary) and a 1080p primary. 

A gnome-shell crash occurs when a user is logged in gnome and then gnome is locked from inactivity. If from another TTY a different user logs in (in my case, root), then going back to gnome, the initial user's session crashes and in most cases all open programs are lost.

A log speaks a thousand words: https://pastebin.com/uq0pE69q

Is this an issue with multi-monitors, or am I mistaking something?

**Comment by jbicha** [comment]
> Is this an issue with multi-monitors, or am I mistaking something?

Does the crash happen if you disable this extension?

**Comment by siddhanathan** [comment]
I can confirm. Using Ubuntu 17.10 on Gnome 3.26.1 with Intel drivers.

**Comment by Zvezdin** [comment]
The crash doesn't occur every time. I disabled the extension and it hasn't crashes yet (but that doesn't mean it won't). I will reply if this happens with the extension off.

**Comment by al-paca** [comment]
I am seeing the same behavior on 2 different machines.  My Desktop running Arch, Gnome 3.26.1 and nvidia driver.  Log here [https://pastebin.com/Nd3a3BXe](url)

The second machine is a Laptop, also running Arch and Gnome 3.26.1.  In the case of this machine, the crash only happens if I have additional monitors plugged in, not when just running the primary display.  Afraid I do not have that machine to post a log from it at this time.

In both cases, disabling the add-on resolves the crash when logging back in from lock screen.

**Comment by kevn-xyz** [comment]
I was able to trigger this error by disabling and re-enabling the extension. ef06b05 seems to have fixed this for me.

**Comment by TZanke** [comment]
Possible backport for Ubuntu 16 LTS with Gnome 3.18 ? I am affected by this since some months.
