### ISSUE TITLE
Does not respect date / time format from gnome-shell-clock-override

### ISSUE THREAD

**Issue by isleshocky77** [spin83/multi-monitors-add-on#68]
I'm not 100% whether to put this in the [gnome-shell-clock-override](https://github.com/stuartlangridge/gnome-shell-clock-override) add-on, or here; but I'll start here.

I'm overriding the date/time format using [gnome-shell-clock-override](https://github.com/stuartlangridge/gnome-shell-clock-override), with the multi-monitor-add-on extension it only overrides the clock on the primary monitor; the clocks on the additional monitors do not respect this format.

**Comment by spin83** [comment]
In Gnome shell one extensions cannot depend on another, so it’s not possible in a reliable way to modify parameters of another extension.

**Comment by Skillzore** [comment]
Well, you really don't need to modify anything on another extension. We just need to check if the other extension is present and use it to display the time, or rather use its "format string" to change how the Gnome Shell clock is displayed.

**Comment by da2x** [comment]
I don’t see an easy way to implement this. The format string set in the gnome-shell-clock-override extension is stored in the following gsetting:
/org/gnome/shell/extensions/clock_override/override-string

The standard formats could be supported by copying this format string, but some of the extensions added in gnome-shell-clock-override wouldn’t work.

**Comment by spin83** [comment]
The ‘format string’ is not enough, we need the rest of functionality from the gnome-shell-clock-override extension. And we can’t acquire this functionality in reliable way because of extension dependency hell. We can’t even detect correctly if this second extension is present in gnome-shell.

Generally it’s problem with gnome-shell extension system.

**Comment by Skillzore** [comment]
That's too bad then. Does anyone know where gnome stores the clock string in ubuntu 18.04 so I can edit it myself? Also so I can look into making an extension that writes to it so that multi monitors will display the change on all monitors. What does multi monitor actual fetch to display the copies?

**Comment by spin83** [comment]
You can look into this two classes [Calendar](https://gitlab.gnome.org/GNOME/gnome-shell/blob/3.30.2/js/ui/calendar.js#L364) and [MultiMonitorsCalendar](https://github.com/spin83/multi-monitors-add-on/blob/9c023670ee8d6f524d0037448e1513dfa1dc1570/multi-monitors-add-on%40spin83/mmcalendar.js#L43)

**Comment by brandl-muc** [comment]
So I filed the same bug in gnome-shell-clock-override. I was hoping to be able to fix it there by iterating over all panels and setting the clock string on each of them. This would not introduce any dependency.
However I do not know if this is possible and wanted to find out by looking at the source of this plugin. But I'm not really experienced in JavaScript and even less so with Gnome/glib.

So anybody out there who can tell me right away that my idea won't work? Or maybe it could work like that and someone can give me a pointer?
