### ISSUE TITLE
Gnome 3.34 , "actor" now readonly and break multi monitor features

### ISSUE THREAD

**Issue by RaphaelRochet** [spin83/multi-monitors-add-on#95]
Hi,
Do you plan to work on gnome 3.34 compatibility ?

Looks like there's a lot of work as "actor" is deprecated and replaced by a read-only getter. Log says :
`TypeError: setting getter-only property "actor"`
when one try to enable features.

**Comment by Silarn** [comment]
It's a bit strange because this does seem to be true for base St classes, but the core js, for the most part, hasn't been updated to adhere to this yet.

There's a PR that would fix this but it has yet to be merged and this doesn't apply to 3.34.

So there's a mix of partial conversions while leaving actor references on a number of base classes alone.

They also refactored some of the extension handling and events, so one of those references had to be changed.

And they are phasing out the use of Tween to handle animations in favor of native Clutter attribute easeing.

It did get tricky with updating class definitions to inherit directly from St.Widget as this requires you to expose the accessible properties by writing the definitions when registering the GObject. In addition, some of these 'public' properties had their names changed and had to be adjusted in order to be referenced correctly in the core code.

**Comment by BlackDex** [comment]
@Silarn i Tried your code, but there is no panel appearing on my second monitor.
I do get the multi-monitor icon in the tray, but that is it.

**Comment by Silarn** [comment]
@BlackDex Are you getting any errors in your journal or in looking glass? I did find an oversight in one of the destructors, but I doubt that would cause it to fail. This version does require 3.34 as it has some breaking changes.

**Comment by Silarn** [comment]
spin83's recent update is working for me.
